//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDAL
{
    using Foolproof;
    using RestaurantDAL.Model;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int BID { get; set; }

        [Required(ErrorMessage = "Please Enter Your Name")]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Please Enter Valid Name")]
        [StringLength(50,ErrorMessage ="Please Enter a short name")]
        public string Customer_Name { get; set; }

        [Required(ErrorMessage = "Please Specify no Of people")]
        public Nullable<int> No_Of_People { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Please Enter Your ContactNo")]
        public string Contact_No { get; set; }

        [StringLength(45,ErrorMessage ="Please Enter A Short Message")]
        public string Special_Request { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public System.DateTime Booking_Time_And_Date { get; set; }

        [Required(ErrorMessage = "Please Enter You Time of Arrival")]
        [DisplayName("Time Arrival")]
        [ValidForwardDate(ErrorMessage = "Arrival Date can not be greater than current date")]
        public System.DateTime Time_Arrival { get; set; }

        [Required(ErrorMessage = "Please Enter You Time of Departure")]
        [DisplayName("Time Departure")]
        [GreaterThan("Time_Arrival")]
        public Nullable<System.DateTime> Time_Departure { get; set; }
        public int Table_No { get; set; }
        public string Booking_Status { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> res_id { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Order Order { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
