//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDAL
{
    using RestaurantDAL.Model;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Customer_Id { get; set; }

        [Required(ErrorMessage = "Enter your Email")]
        [StringLength(25)]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$", ErrorMessage = "Please Enter Correct mail Address")]
        public string Email { get; set; }

        [DataType(DataType.Text)]
        [DisplayName("Name")]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Please Enter Valid Name")]
        [Required(ErrorMessage = "Please Enter Your Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Enter your Mobile Number")]
        [StringLength(10, ErrorMessage = "Mobile No should Contain 10 Digits Only", MinimumLength = 10)]
        public string MobileNo { get; set; }

        [Required(ErrorMessage = "Enter your password")]
        [StringLength(40,ErrorMessage ="Cannot Be Greater Than 40")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [ValidBirthday(ErrorMessage = "Birth Date can not be greater than current date")]
        public System.DateTime Birthday { get; set; }
        public bool Strike1 { get; set; }
        public bool Strike2 { get; set; }
        public bool Strike3 { get; set; }
        public Nullable<int> wallet_id { get; set; }
        public string Customer_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
