//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDAL
{
    using RestaurantDAL.Model;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        public int EV_ID { get; set; }

        [Required(ErrorMessage ="Please Enter Event Name")]
        [StringLength(25)]
        public string Event_Name { get; set; }

        public string Event_Image { get; set; }

        [Required(ErrorMessage = "Please Enter Event Description")]
        [StringLength(450)]
        public string Event_Description { get; set; }

        [Display(Name = "Event Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [ValidEventDate(ErrorMessage = "Event Date can not be lesser than current date")]
        [RegularExpression(@"([12]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]))", ErrorMessage = "Please Enter Valid Name")]
        public System.DateTime Event_date { get; set; }
        public Nullable<int> Res_Id { get; set; }

        [DataType(DataType.Time,ErrorMessage ="Please Enter a valid Time")]
        [Required(ErrorMessage ="Time is Required")]
        public System.TimeSpan event_time { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
