//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Food_Id { get; set; }
        [Required(ErrorMessage ="Enter Food Name"),StringLength(20)]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Please Enter Valid Name")]
        public string Food_Name { get; set; }
        [Required(ErrorMessage ="Enter the Food Price")]

        public decimal Food_Price { get; set; }
        [Required(ErrorMessage ="Enter Veg or NonVeg")]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Please Enter Veg or Non Veg")]
        [StringLength(10,ErrorMessage ="Cannot take more than 10 characters")]
        public string Veg_NonVeg { get; set; }
        [Required(ErrorMessage ="Enter  the Cuisine")]
        [StringLength(25,ErrorMessage ="Cannot be greater than 25 characters")]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Please Enter Valid Cuisine Name Without Numbers")]
        public string Cuisine { get; set; }
        public Nullable<int> res_id { get; set; }
        public string Food_Image { get; set; }
        [Required(ErrorMessage ="Enter the FoodType")]
        [RegularExpression(@"^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Please Enter Valid Food Type")]
        [StringLength(15,ErrorMessage ="Cannot take more than 15 values")]
        public string Food_Type { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
