//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Notify_Id { get; set; }
        public string Notify_From { get; set; }
        public Nullable<int> Notify_From_Id { get; set; }
        public string Notify_To { get; set; }
        public Nullable<int> Notify_To_Id { get; set; }
        public string Notify_Head { get; set; }
        public string Notify_Description { get; set; }
        public Nullable<System.DateTime> Notify_Time { get; set; }
    }
}
