//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDAL
{
    using Foolproof;
    using RestaurantDAL.Model;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Offer
    {
        public int Off_Id { get; set; }
        [Required,StringLength(25)]

        public string Offer_name { get; set; }
        [Required,StringLength(250)]
        public string Offer_Desc { get; set; }
        
        [Display(Name = "Offer Valid To")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [GreaterThan("offer_valid_from")]
        public System.DateTime Offer_Valid_To { get; set; }
        public Nullable<int> Res_Id { get; set; }
        
        [Display(Name = "Offer Valid From")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [ValidForwardDate(ErrorMessage = "Offer Date can not be smaller than current date")]
        public System.DateTime offer_valid_from { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
